import XCTest
@testable import BolusCore

/// Vectors generated by `backend/scripts/generate_shared_vectors.py` from the Python
/// reference implementation and checked on both sides (`backend/tests/test_shared_vectors.py`).
final class SharedVectorTests: XCTestCase {
    private func same(_ a: Double?, _ b: Double?) -> Bool {
        switch (a, b) {
        case (nil, nil): return true
        case let (x?, y?): return (x.isNaN && y.isNaN) || x == y
        default: return false
        }
    }

    func testBolusVectorsMatchPython() throws {
        let cases = try XCTUnwrap(Fixture.json("bolus_vectors")["cases"]?.arrayValue)
        XCTAssertGreaterThan(cases.count, 2000)
        var checked = 0
        for item in cases {
            let id = item.string("id") ?? "?"
            let at = try XCTUnwrap(ISODate.parse(item.string("at") ?? ""))
            let input = try XCTUnwrap(item["input"])
            let engineInput = BolusEngine.Input(
                glucose: vectorDouble(input["glucose"]), unit: input.string("unit") ?? "",
                carbs: try XCTUnwrap(vectorDouble(input["carbs"])), icr: try XCTUnwrap(vectorDouble(input["icr"])),
                isf: try XCTUnwrap(vectorDouble(input["isf"])), target: try XCTUnwrap(vectorDouble(input["target"])),
                correctAbove: try XCTUnwrap(vectorDouble(input["correct_above"])), dia: try XCTUnwrap(vectorDouble(input["dia"])),
                iob: try XCTUnwrap(vectorDouble(input["iob"])), maxBolus: try XCTUnwrap(vectorDouble(input["max_bolus"])),
                measuredAt: input.string("measured_at").flatMap(ISODate.parse),
                bolusIncrement: vectorDouble(input["bolus_increment"]))
            let result = BolusEngine.calculate(engineInput, at: at)
            let expected = try XCTUnwrap(item["expected"])
            XCTAssertEqual(result.algorithmVersion, expected.string("algorithm_version"), id)
            XCTAssertEqual(result.calculationStatus.rawValue, expected.string("calculation_status"), id)
            XCTAssertEqual(result.warnings, expected["warnings"]?.arrayValue?.compactMap(\.stringValue), id)
            let fields: [(String, Double?)] = [
                ("recommended_bolus", result.recommendedBolus), ("meal_bolus", result.mealBolus),
                ("raw_correction_bolus", result.rawCorrectionBolus), ("correction_bolus", result.correctionBolus),
                ("iob", result.iob), ("iob_adjustment", result.iobAdjustment), ("cycle_adjustment", result.cycleAdjustment),
                ("personalization_adjustment", result.personalizationAdjustment), ("unrounded_bolus", result.unroundedBolus),
                ("rounding_increment", result.roundingIncrement), ("rounding_adjustment", result.roundingAdjustment),
            ]
            for (key, value) in fields {
                XCTAssertTrue(same(value, vectorDouble(expected[key])), "\(id) \(key): swift \(String(describing: value)) python \(String(describing: expected[key]))")
            }
            checked += 1
        }
        XCTAssertEqual(checked, cases.count)
    }

    func testIOBVectorsMatchPython() throws {
        let cases = try XCTUnwrap(Fixture.json("iob_vectors")["cases"]?.arrayValue)
        XCTAssertGreaterThan(cases.count, 600)
        for item in cases {
            let id = item.string("id") ?? "?"
            let at = try XCTUnwrap(ISODate.parse(item.string("at") ?? ""))
            let doses = try (item["doses"]?.arrayValue ?? []).map { dose in
                AdministeredDose(units: try XCTUnwrap(vectorDouble(dose["units"])),
                                 administeredAt: try XCTUnwrap(ISODate.parse(dose.string("administered_at") ?? "")),
                                 diaHours: try XCTUnwrap(vectorDouble(dose["dia_hours"])),
                                 insulinType: InsulinType(rawValue: dose.string("insulin_type") ?? "") ?? .rapid)
            }
            if item.string("error") != nil {
                XCTAssertThrowsError(try IOBEngine.calculate(doses, at: at), id)
            } else {
                XCTAssertEqual(try IOBEngine.calculate(doses, at: at), vectorDouble(item["expected"]), id)
            }
        }
    }

    func testPythonNumericVectors() throws {
        let root = try Fixture.json("numeric_vectors")
        for item in root["round"]?.arrayValue ?? [] {
            let x = try XCTUnwrap(item.double("x"))
            let n = Int(try XCTUnwrap(item.double("n")))
            XCTAssertEqual(PyFloat.round(x, n), item.double("expected"), "round(\(x), \(n))")
        }
        let stats = root["statistics"]?.arrayValue ?? []
        XCTAssertGreaterThan(stats.count, 100)
        for item in stats {
            let values = (item["values"]?.arrayValue ?? []).compactMap(\.doubleValue)
            XCTAssertEqual(PyStatistics.mean(values), item.double("mean"))
            XCTAssertEqual(PyStatistics.median(values), item.double("median"))
            XCTAssertEqual(PyStatistics.pstdev(values), item.double("pstdev"))
        }
    }
}

/// Analytics parity: bit-identical where data exists; `nil` (Swift) ↔ `0.0` (Python)
/// where a period has no records of that type.
final class AnalyticsVectorTests: XCTestCase {
    private func assertMetric(_ swift: Double?, _ python: JSONValue?, records: Int, _ message: String) {
        if let swift {
            XCTAssertEqual(swift, python?.doubleValue, message)
        } else {
            XCTAssertEqual(records, 0, message)
            XCTAssertEqual(python?.doubleValue ?? 0, 0, message)
        }
    }

    private func assertSummary(_ s: AnalyticsEngine.Summary, _ p: JSONValue, _ id: String) {
        XCTAssertEqual(Double(s.sampleSize), p.double("sample_size"), id)
        XCTAssertEqual(s.coverageMethod, p.string("coverage_method"), id)
        let exact: [(String, Double?)] = [
            ("mean_glucose", s.meanGlucose), ("median_glucose", s.medianGlucose), ("min", s.min), ("max", s.max),
            ("standard_deviation", s.standardDeviation), ("coefficient_of_variation", s.coefficientOfVariation),
            ("tir", s.tir), ("tbr", s.tbr), ("tar", s.tar),
        ]
        for (key, value) in exact { XCTAssertEqual(value, p.double(key), "\(id) \(key)") }
        assertMetric(s.dailyInsulin, p["daily_insulin"], records: s.insulinRecords, "\(id) daily_insulin")
        assertMetric(s.basalInsulin, p["basal_insulin"], records: s.basalRecords, "\(id) basal_insulin")
        assertMetric(s.bolusInsulin, p["bolus_insulin"], records: s.bolusRecords, "\(id) bolus_insulin")
        assertMetric(s.carbsPerDay, p["carbs_per_day"], records: s.mealRecords, "\(id) carbs_per_day")
        assertMetric(s.caloriesPerDay, p["calories_per_day"], records: s.mealRecords, "\(id) calories_per_day")
        assertMetric(s.correctionsPerDay, p["corrections_per_day"], records: s.insulinRecords, "\(id) corrections_per_day")
        XCTAssertEqual(Double(s.days), p.double("days"), id)
    }

    func testAnalyticsVectorsMatchPython() throws {
        let cases = try XCTUnwrap(Fixture.json("analytics_vectors")["cases"]?.arrayValue)
        XCTAssertEqual(cases.count, 80)
        for item in cases {
            let id = item.string("id") ?? "?"
            let zone = try XCTUnwrap(TimeZone(identifier: item.string("timezone") ?? ""))
            let from = try XCTUnwrap(LocalDate(iso: item.string("date_from") ?? ""))
            let to = try XCTUnwrap(LocalDate(iso: item.string("date_to") ?? ""))
            let entries = try (item["entries"]?.arrayValue ?? []).map { raw -> DiaryRecord in
                DiaryRecord(id: try XCTUnwrap(UUID(uuidString: raw.string("id") ?? "")),
                            kind: try XCTUnwrap(EntryKind(rawValue: raw.string("kind") ?? "")),
                            occurredAt: try XCTUnwrap(ISODate.parse(raw.string("occurred_at") ?? "")),
                            data: try XCTUnwrap(raw["data"]))
            }
            let expected = try XCTUnwrap(item["expected"])
            assertSummary(AnalyticsEngine.summarize(entries, days: to.days(since: from) + 1), try XCTUnwrap(expected["metrics"]), id)

            let hourly = AnalyticsEngine.hourlyProfile(entries, timeZone: zone)
            let expectedHourly = expected["hourly"]?.arrayValue ?? []
            XCTAssertEqual(hourly.count, expectedHourly.count, id)
            for (point, python) in zip(hourly, expectedHourly) {
                XCTAssertEqual(Double(point.hour), python.double("hour"), id)
                XCTAssertEqual(point.mean, python.double("mean"), "\(id) hour \(point.hour)")
                XCTAssertEqual(Double(point.count), python.double("count"), id)
            }

            let daily = AnalyticsEngine.dailyBreakdown(entries, from: from, to: to, timeZone: zone)
            let expectedDaily = expected["daily"]?.arrayValue ?? []
            XCTAssertEqual(daily.count, expectedDaily.count, id)
            for (row, python) in zip(daily, expectedDaily) {
                XCTAssertEqual(row.date.description, python.string("date"), id)
                assertSummary(row.summary, python, "\(id) \(row.date)")
                let activities = entries.filter { $0.kind == .activity && LocalDate(date: $0.occurredAt, timeZone: zone) == row.date }.count
                assertMetric(row.activityMinutes, python["activity_minutes"], records: activities, "\(id) activity_minutes")
            }

            let observations = AnalyticsEngine.activityResponse(entries)
            let expectedObservations = expected["activity_response"]?.arrayValue ?? []
            XCTAssertEqual(observations.count, expectedObservations.count, id)
            for (observation, python) in zip(observations, expectedObservations) {
                XCTAssertEqual(observation.activityID, python.string("activity_id"), id)
                XCTAssertEqual(observation.name, python.string("name"), id)
                XCTAssertEqual(observation.before, python.double("before"), id)
                XCTAssertEqual(observation.after, python.double("after"), id)
                XCTAssertEqual(observation.change, python.double("change"), id)
                XCTAssertEqual(observation.source, python.string("source"), id)
            }
        }
    }

    func testTimedeltaMinutesMatchesCPython() {
        XCTAssertEqual(Micros.pythonTimedelta(minutes: 45), 2_700_000_000)
        XCTAssertEqual(Micros.pythonTimedelta(minutes: 0.1), 6_000_000)
        XCTAssertEqual(Micros.pythonTimedelta(minutes: 55.3), 3_318_000_000)
        XCTAssertEqual(Micros.pythonTimedelta(minutes: 1e-8), 1)
    }
}
