"""Frozen initial schema; changes require a new migration."""
from alembic import op
import sqlalchemy as sa
revision="0001"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('glucose_unit', sa.String(length=10), nullable=False),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('theme_id', sa.String(length=30), nullable=False),
    sa.Column('mascot_id', sa.String(length=30), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bolus_calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculated_at', sa.String(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('calculation_snapshot', sa.JSON(), nullable=False),
    sa.Column('actual_bolus', sa.Float(), nullable=True),
    sa.Column('confirmed_entry_id', sa.String(), nullable=True),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bolus_calculations_user_id'), 'bolus_calculations', ['user_id'], unique=False)
    op.create_table('custom_foods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_recipe', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_foods_user_id'), 'custom_foods', ['user_id'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=False),
    sa.Column('actual_ovulation_date', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_user_id'), 'cycles', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id')
    )
    op.create_index(op.f('ix_entries_kind'), 'entries', ['kind'], unique=False)
    op.create_index(op.f('ix_entries_occurred_at'), 'entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('date_from', sa.String(), nullable=False),
    sa.Column('date_to', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_jobs_user_id'), 'report_jobs', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('csrf', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('therapy_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.String(), nullable=False),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version')
    )
    op.create_index(op.f('ix_therapy_profiles_user_id'), 'therapy_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapy_profiles_user_id'), table_name='therapy_profiles')
    op.drop_table('therapy_profiles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_report_jobs_user_id'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_occurred_at'), table_name='entries')
    op.drop_index(op.f('ix_entries_kind'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_cycles_user_id'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_custom_foods_user_id'), table_name='custom_foods')
    op.drop_table('custom_foods')
    op.drop_index(op.f('ix_bolus_calculations_user_id'), table_name='bolus_calculations')
    op.drop_table('bolus_calculations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
